version: '3' 

services:
  api:
    image: api-test
    ports:
      - 3000:3000
    build: .
    links:
      - database
    depends_on:
      - database
  database: 
    image: postgres 
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"